# normal calculator using tkinter

from tkinter import *
from tkinter import ttk

root = Tk()
root.title("Calculator")
root.geometry("400x400")
frame = ttk.Frame(root, padding="3 3 12 12")
frame.grid(column=0, row=0, sticky=(N, W, E, S))
displayLabel = ttk.Label(frame, text="0")
displayLabel.grid(column=0, row=0, sticky=E,columnspan=4)
clearButton = ttk.Button(frame, text="C")
clearButton.grid(column=0, row=1, sticky=(W, E))
rootButton = ttk.Button(frame, text="√")
rootButton.grid(column=1, row=1, sticky=(W, E))
powerButton = ttk.Button(frame, text="x^y")
powerButton.grid(column=2, row=1, sticky=(W, E))
percentageButton = ttk.Button(frame, text="%")
percentageButton.grid(column=3, row=1, sticky=(W, E))
oneButton = ttk.Button(frame, text="1")
oneButton.grid(column=0, row=2, sticky=(W, E))
twoButton = ttk.Button(frame, text="2")
twoButton.grid(column=1, row=2, sticky=(W, E))
threeButton = ttk.Button(frame, text="3")
threeButton.grid(column=2, row=2, sticky=(W, E))
fourButton = ttk.Button(frame, text="4")
fourButton.grid(column=0, row=3, sticky=(W, E))
fiveButton = ttk.Button(frame, text="5")
fiveButton.grid(column=1, row=3, sticky=(W, E))
sixButton = ttk.Button(frame, text="6")
sixButton.grid(column=2, row=3, sticky=(W, E))
sevenButton = ttk.Button(frame, text="7")
sevenButton.grid(column=0, row=4, sticky=(W, E))
eightButton = ttk.Button(frame, text="8")
eightButton.grid(column=1, row=4, sticky=(W, E))
nineButton = ttk.Button(frame, text="9")
nineButton.grid(column=2, row=4, sticky=(W, E))
zeroButton = ttk.Button(frame, text="0")
zeroButton.grid(column=0, row=5, sticky=(W, E))
addButton = ttk.Button(frame, text="+")
addButton.grid(column=3, row=2, sticky=(W, E))
subtractButton = ttk.Button(frame, text="-")
subtractButton.grid(column=3, row=3, sticky=(W, E))
multiplyButton = ttk.Button(frame, text="*")
multiplyButton.grid(column=3, row=4, sticky=(W, E))
divideButton = ttk.Button(frame, text="/")
divideButton.grid(column=3, row=5, sticky=(W, E))
equalsButton = ttk.Button(frame, text="=")
equalsButton.grid(column=2, row=5, sticky=(W, E))
dotButton = ttk.Button(frame, text=".")
dotButton.grid(column=1, row=5, sticky=(W, E))
root.mainloop()
