from tkinter import *
from tkinter import ttk


root = Tk()
root.title("Payment Calculator")
root.geometry("400x400")
frame = ttk.Frame(root, padding="3 3 12 12")
frame.grid(column=0, row=0, sticky=(N, W, E, S))
annualRateLabel = ttk.Label(frame, text="Annual Interest Rate")
annualRateLabel.grid(column=0, row=0, sticky=W)
annualRate = ttk.Entry(frame)
annualRate.grid(column=1, row=0, sticky=(W, E))
annualRate.insert(0,"4")
numberOfPaymentsLabel = ttk.Label(frame, text="Number of Payments")
numberOfPaymentsLabel.grid(column=0, row=1, sticky=W)
numberOfPayments = ttk.Entry(frame)
numberOfPayments.grid(column=1, row=1, sticky=(W, E))
numberOfPayments.insert(0,"60")
loanPrincipleLabel = ttk.Label(frame, text="Loan Principle")
loanPrincipleLabel.grid(column=0, row=2, sticky=W)
loanPrinciple = ttk.Entry(frame)
loanPrinciple.grid(column=1, row=2, sticky=(W, E))
loanPrinciple.insert(0,"200000")
monthlyPaymentLabel = ttk.Label(frame, text="Monthly Payment")
monthlyPaymentLabel.grid(column=0, row=3, sticky=W)
monthlyPayment = ttk.Entry(frame)
monthlyPayment.grid(column=1, row=3, sticky=(W, E))
monthlyPayment.insert(0,"225.79")
remainingLoanLabel = ttk.Label(frame, text="Remaining Loan")
remainingLoanLabel.grid(column=0, row=4, sticky=W)
remainingLoan = ttk.Entry(frame)
remainingLoan.grid(column=1, row=4, sticky=(W, E))
remainingLoan.insert(0,"0")
finalBalanceButton = ttk.Button(frame, text="Final Balance")
finalBalanceButton.grid(column=0, row=5, sticky=(W, E))
monthlyPaymentButton = ttk.Button(frame, text="Monthly Payment")
monthlyPaymentButton.grid(column=1, row=5, sticky=(W, E))
quitButton = ttk.Button(frame, text="Quit")
quitButton.grid(column=2, row=5, sticky=(W, E))
root.mainloop()